import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest':  '#0e0e0e',
        'surface-container-low':     '#1c1b1b',
        'surface-container':         '#201f1f',
        'surface-container-high':    '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-bright':            '#3a3939',
        'surface-dim':               '#131313',
        'surface-variant':           '#353534',
        'surface':                   '#131313',
        'background':                '#131313',
        'on-surface':                '#e5e2e1',
        'on-surface-variant':        '#baccb0',
        'on-background':             '#e5e2e1',
        'secondary':                 '#c8c6c5',
        'secondary-container':       '#474746',
        'on-secondary':              '#313030',
        'on-secondary-container':    '#b7b5b4',
        'secondary-fixed':           '#e5e2e1',
        'secondary-fixed-dim':       '#c8c6c5',
        'on-secondary-fixed':        '#1c1b1b',
        'on-secondary-fixed-variant':'#474746',
        'primary':                   '#efffe3',
        'primary-container':         '#39ff14',
        'on-primary':                '#053900',
        'on-primary-container':      '#107100',
        'primary-fixed':             '#79ff5b',
        'primary-fixed-dim':         '#2ae500',
        'on-primary-fixed':          '#022100',
        'on-primary-fixed-variant':  '#095300',
        'inverse-primary':           '#106e00',
        'surface-tint':              '#2ae500',
        'tertiary':                  '#fff8f7',
        'tertiary-container':        '#ffd3ce',
        'on-tertiary':               '#442927',
        'on-tertiary-container':     '#7a5955',
        'tertiary-fixed':            '#ffdad6',
        'tertiary-fixed-dim':        '#e7bdb8',
        'on-tertiary-fixed':         '#2c1513',
        'on-tertiary-fixed-variant': '#5d3f3c',
        'error':                     '#ffb4ab',
        'error-container':           '#93000a',
        'on-error':                  '#690005',
        'on-error-container':        '#ffdad6',
        'outline':                   '#85967c',
        'outline-variant':           '#3c4b35',
        'inverse-surface':           '#e5e2e1',
        'inverse-on-surface':        '#313030',
      },
      spacing: {
        'xs':            '8px',
        'base':          '4px',
        'sm':            '12px',
        'md':            '16px',
        'lg':            '24px',
        'xl':            '32px',
        'gutter':        '16px',
        'margin-mobile': '20px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      fontSize: {
        'display-stat':       ['48px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':        ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md':        ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm':            ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps':         ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}

export default config
